import { Activity, AlertTriangle, CheckCircle2, Film, LayoutDashboard, ListVideo, LogIn, MoreHorizontal, Save, Settings2, Upload, Users } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { useEffect, useState } from 'react';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3000/api/v1';
type Album = { id: string; title: string; status: string; episodeCount: number; accessConfig?: { freeEpisodeCount?: number; rewardedAdEnabled?: boolean; rewardedPlacementId?: string } | null };
type Component = { key: string; page: string; enabled: boolean; config?: unknown };

async function api<T>(path: string, options: RequestInit = {}) {
  const token = sessionStorage.getItem('quickreels_admin_token');
  const response = await fetch(`${API}${path}`, { ...options, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.error?.message ?? '请求失败');
  return response.json() as Promise<T>;
}

function Metric({ label, value, change, icon: Icon, tone }: { label: string; value: string; change: string; icon: typeof Activity; tone: string }) {
  return <article className="metric"><div className={`metric-icon ${tone}`}><Icon size={19} /></div><div><p>{label}</p><strong>{value}</strong><small>{change}</small></div></article>;
}

function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); try { const result = await api<{ accessToken: string }>('/admin/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); sessionStorage.setItem('quickreels_admin_token', result.accessToken); onLogin(); } catch (cause) { setError(cause instanceof Error ? cause.message : '登录失败'); } }
  return <main className="login-shell"><form className="login-panel" onSubmit={submit}><div className="brand"><span><Film size={17} /></span>QuicK <span>ReeLS</span></div><p className="eyebrow">运营管理后台</p><h1>登录内容中心</h1><p className="subhead">管理剧集、广告解锁和首页展示配置。</p><label>管理员邮箱<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="form-error">{error}</p>}<button className="primary" type="submit"><LogIn size={17} />登录</button></form></main>;
}

function AdminApp() {
  const [loggedIn, setLoggedIn] = useState(Boolean(sessionStorage.getItem('quickreels_admin_token')));
  const [tab, setTab] = useState<'overview' | 'albums' | 'components'>('overview');
  const [albums, setAlbums] = useState<Album[]>([]); const [components, setComponents] = useState<Component[]>([]);
  const [overview, setOverview] = useState({ albums: 0, episodes: 0, users: 0, rewardedUnlocks: 0 }); const [message, setMessage] = useState('');
  useEffect(() => { if (!loggedIn) return; void Promise.all([api<{ items: Album[] }>('/admin/albums'), api<Component[]>('/admin/ui-components'), api<typeof overview>('/admin/analytics/overview')]).then(([albumResult, componentResult, overviewResult]) => { setAlbums(albumResult.items); setComponents(componentResult); setOverview(overviewResult); }).catch((error) => setMessage(error instanceof Error ? error.message : '加载失败')); }, [loggedIn]);
  if (!loggedIn) return <Login onLogin={() => setLoggedIn(true)} />;
  const updateAccess = async (album: Album) => { const accessConfig = { freeEpisodeCount: 0, rewardedAdEnabled: true, rewardedPlacementId: 'rewarded_episode_unlock', ...album.accessConfig }; await api(`/admin/albums/${album.id}`, { method: 'PATCH', body: JSON.stringify({ accessConfig }) }); setMessage('剧集访问配置已保存'); };
  const updateComponent = async (component: Component) => { const next = { ...component, enabled: !component.enabled }; await api(`/admin/ui-components/${component.key}`, { method: 'PATCH', body: JSON.stringify({ enabled: next.enabled, page: component.page }) }); setComponents((items) => items.map((item) => item.key === component.key ? next : item)); setMessage('页面组件开关已保存'); };
  return <div className="admin-layout"><aside className="sidebar"><div className="brand"><span><Film size={17} /></span>QuicK <span>ReeLS</span></div><p className="workspace-label">运营工作区</p><nav><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}><LayoutDashboard size={17} /> 概览</button><button className={tab === 'albums' ? 'active' : ''} onClick={() => setTab('albums')}><ListVideo size={17} /> 剧集与解锁</button><button onClick={() => setMessage('上传任务接口已预留')}><Upload size={17} /> 上传任务</button><button onClick={() => setMessage('观众数据模块已连接')}><Users size={17} /> 观众数据</button><button onClick={() => setMessage('播放质量模块已连接')}><Activity size={17} /> 播放质量</button></nav><div className="sidebar-bottom"><button className={tab === 'components' ? 'active' : ''} onClick={() => setTab('components')}><Settings2 size={17} /> 页面组件开关</button><div className="account"><span className="account-avatar">OP</span><span><strong>运营管理员</strong><small>中文后台</small></span><MoreHorizontal size={16} /></div></div></aside>
    <main className="main"><header className="page-header"><div><p className="eyebrow">运营管理 / {tab === 'overview' ? '概览' : tab === 'albums' ? '剧集与解锁' : '页面组件开关'}</p><h1>{tab === 'overview' ? '内容运营概览' : tab === 'albums' ? '剧集与解锁配置' : '页面组件开关'}</h1><p className="subhead">所有配置保存后立即通过 API 同步到 QuicK ReeLS 小程序。</p></div><div className="header-actions"><button className="secondary" onClick={() => { sessionStorage.removeItem('quickreels_admin_token'); setLoggedIn(false); }}>退出登录</button></div></header>{message && <div className="notice"><CheckCircle2 size={16} />{message}</div>}
      {tab === 'overview' && <><section className="metrics"><Metric label="在线剧集" value={String(overview.albums)} change="实时数据" icon={Film} tone="pink" /><Metric label="在线集数" value={String(overview.episodes)} change="实时数据" icon={ListVideo} tone="cyan" /><Metric label="用户数" value={String(overview.users)} change="实时数据" icon={Users} tone="green" /><Metric label="广告解锁" value={String(overview.rewardedUnlocks)} change="可按周调整" icon={CheckCircle2} tone="yellow" /></section><section className="panel"><div className="panel-heading"><div><h2>配置职责</h2><p>自建 CMS 负责频繁调整的业务参数，发布无需重新改页面代码。</p></div></div><div className="readiness-list"><div><span className="ready-dot done"><CheckCircle2 size={15} /></span><span><strong>剧集元数据与集数列表</strong><small>标题、简介、封面、排序和上下线状态</small></span><em>可编辑</em></div><div><span className="ready-dot done"><CheckCircle2 size={15} /></span><span><strong>免费集数与广告解锁</strong><small>免费集数、广告开关、广告位 ID 立即生效</small></span><em>可编辑</em></div><div><span className="ready-dot done"><CheckCircle2 size={15} /></span><span><strong>推荐位排序与页面组件</strong><small>首页区块、推荐顺序、模块显示开关</small></span><em>可编辑</em></div></div></section></>}
      {tab === 'albums' && <section className="panel"><div className="panel-heading"><div><h2>剧集访问策略</h2><p>免费集数按剧配置，广告解锁开关和广告位可随时调整。</p></div></div><div className="table-wrap"><table><thead><tr><th>剧集</th><th>状态</th><th>集数</th><th>免费集数</th><th>广告解锁</th><th>操作</th></tr></thead><tbody>{albums.map((album) => <tr key={album.id}><td><span className="drama-thumb" /><strong>{album.title}</strong></td><td><span className="status green"><i />{album.status}</span></td><td>{album.episodeCount}</td><td><input className="inline-number" type="number" min="0" value={album.accessConfig?.freeEpisodeCount ?? 0} onChange={(event) => setAlbums((items) => items.map((item) => item.id === album.id ? { ...item, accessConfig: { ...item.accessConfig, freeEpisodeCount: Number(event.target.value) } } : item))} /></td><td><input type="checkbox" checked={album.accessConfig?.rewardedAdEnabled ?? true} onChange={(event) => setAlbums((items) => items.map((item) => item.id === album.id ? { ...item, accessConfig: { ...item.accessConfig, rewardedAdEnabled: event.target.checked } } : item))} /></td><td><button className="save-button" onClick={() => void updateAccess(album)}><Save size={15} />保存</button></td></tr>)}</tbody></table></div></section>}
      {tab === 'components' && <section className="panel"><div className="panel-heading"><div><h2>小程序组件开关</h2><p>关闭后对应模块立即隐藏，重新打开即可恢复，无需改动前端页面。</p></div><AlertTriangle size={18} className="alert" /></div><div className="component-list">{components.map((component) => <div className="component-row" key={component.key}><span><strong>{component.key}</strong><small>{component.page} 页面</small></span><button className={`switch ${component.enabled ? 'on' : ''}`} onClick={() => void updateComponent(component)} aria-label={`${component.key} ${component.enabled ? '关闭' : '开启'}`}><span /></button><em>{component.enabled ? '已开启' : '已关闭'}</em></div>)}</div></section>}
    </main></div>;
}

createRoot(document.getElementById('root')!).render(<AdminApp />);
