import type { Locale } from '@quickreels/shared-types';

export const supportedLocales: { value: Locale; label: string; short: string }[] = [
  { value: 'en', label: 'English', short: 'EN' },
  { value: 'pt', label: 'Português', short: 'PT' },
  { value: 'fr', label: 'Français', short: 'FR' },
  { value: 'id', label: 'Bahasa Indonesia', short: 'ID' },
  { value: 'ja', label: '日本語', short: 'JA' },
  { value: 'es', label: 'Español', short: 'ES' },
  { value: 'ko', label: '한국어', short: 'KO' },
  { value: 'th', label: 'ไทย', short: 'TH' }
];

const english = {
  home: 'Home', search: 'Search', library: 'My library', profile: 'Profile', featured: 'Featured', continue: 'Continue watching', browse: 'Browse by mood', trending: 'Trending now', fresh: 'Fresh episodes',
  discover: 'Your next obsession starts here.', discoverCopy: 'Short dramas made for the moments between everything else.', viewDrama: 'View drama', seeAll: 'See all', moreToWatch: 'More to watch', stories: 'stories', views: 'views', watched: 'watched', episodes: 'episodes', episode: 'Episode', free: 'FREE',
  watchAd: 'Watch ad to unlock', watchNow: 'Watch now', details: 'Details', about: 'About this drama', cast: 'A new story every night', like: 'Like', liked: 'Liked', save: 'Save', saved: 'Saved', share: 'Share',
  signIn: 'Sign in with TikTok', signInCopy: 'Save your place, collect favorites, and unlock episodes across devices.', guest: 'Guest viewer', history: 'Recently watched', favorites: 'Favorites', settings: 'Settings', language: 'Language', autoplay: 'Autoplay next episode', reducedData: 'Reduce data usage', continueWithoutTapping: 'Continue without tapping', useLessData: 'Use less media data',
  noHistory: 'Your watch history will appear here.', noFavorites: 'Save a drama to build your shelf.', back: 'Back', retry: 'Retry', noResults: 'No dramas match that search.', tryThese: 'Try one of these instead', searchPlaceholder: 'Search dramas or genres', clearSearch: 'Clear search', findNextStory: 'Find your next story.', searchByTitleMoodGenre: 'Search by title, mood, or genre.',
  platformPending: 'Official player pending platform confirmation', platformCopy: 'The official TikTok Mini Drama player is enabled after the app qualification and Player Reference are verified.', openInTikTok: 'Open this Mini inside TikTok to test the official player.', qualificationRequired: 'Qualification evidence and the current Player Reference are required before production playback.',
  preparingPlayer: 'Preparing the official player...', playerReady: 'Player integration is ready for TikTok Preview configuration.', demoMode: 'Demo mode', apiConnected: 'API connected', apiFallback: 'Using local preview data', refresh: 'Refresh', loadingReel: 'Loading your reel...', loadingHistory: 'Loading history...', loadingFavorites: 'Loading favorites...', searching: 'Searching...', openingDrama: 'Opening drama...', preparingEpisode: 'Preparing your episode...', unavailable: 'This drama is unavailable.', upNext: 'Up next', updatingPlayback: 'Updating playback info', episodeLocked: 'This episode is locked or not ready for playback.', rewardedAdRequired: 'Rewarded ad required', playable: 'Playable', unlockEpisode: 'Unlock episode', watchEpisode: 'Watch episode', welcome: 'WELCOME IN', member: 'QUICKREEL MEMBER', syncing: 'Syncing...', unlockFailed: 'Unlock failed. Please try again.', navigation: 'Primary navigation', previousFeatured: 'Previous featured drama', nextFeatured: 'Next featured drama', privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service'
} as const;

type MessageKey = keyof typeof english;
type Messages = Record<MessageKey, string>;
const localize = (overrides: Partial<Messages>): Messages => ({ ...english, ...overrides });

const messages: Record<Locale, Messages> = {
  en: english,
  pt: localize({ home: 'Inicio', search: 'Buscar', library: 'Minha lista', profile: 'Perfil', featured: 'Em destaque', continue: 'Continuar assistindo', browse: 'Explorar por humor', trending: 'Em alta', fresh: 'Novos episodios', discover: 'Sua proxima historia comeca aqui.', discoverCopy: 'Dramas curtos para os momentos entre todas as outras coisas.', seeAll: 'Ver tudo', moreToWatch: 'Mais para assistir', stories: 'historias', views: 'visualizacoes', watched: 'assistido', episodes: 'episodios', episode: 'Episodio', free: 'GRATIS', watchAd: 'Assista ao anuncio para desbloquear', watchNow: 'Assistir agora', details: 'Detalhes', about: 'Sobre este drama', like: 'Curtir', liked: 'Curtido', save: 'Salvar', saved: 'Salvo', share: 'Compartilhar', signIn: 'Entrar com TikTok', signInCopy: 'Salve seu progresso, favorite historias e desbloqueie episodios em todos os dispositivos.', guest: 'Visitante', history: 'Vistos recentemente', favorites: 'Favoritos', settings: 'Configuracoes', language: 'Idioma', autoplay: 'Reproduzir proximo episodio automaticamente', reducedData: 'Reduzir uso de dados', continueWithoutTapping: 'Continuar sem tocar', useLessData: 'Usar menos dados de midia', noHistory: 'Seu historico aparecera aqui.', noFavorites: 'Salve um drama para criar sua lista.', back: 'Voltar', retry: 'Tentar novamente', noResults: 'Nenhum drama corresponde a busca.', tryThese: 'Tente uma destas opcoes', searchPlaceholder: 'Buscar dramas ou generos', clearSearch: 'Limpar busca', findNextStory: 'Encontre sua proxima historia.', searchByTitleMoodGenre: 'Busque por titulo, clima ou genero.', upNext: 'A seguir', syncing: 'Sincronizando...', unlockFailed: 'Falha ao desbloquear. Tente novamente.', unavailable: 'Este drama nao esta disponivel.', openingDrama: 'Abrindo drama...', preparingEpisode: 'Preparando seu episodio...', searching: 'Buscando...', updatingPlayback: 'Atualizando informacoes de reproducao', rewardedAdRequired: 'Anuncio recompensado necessario', playable: 'Disponivel', unlockEpisode: 'Desbloquear episodio', watchEpisode: 'Assistir episodio', welcome: 'BEM-VINDO', member: 'MEMBRO QUICKREEL', navigation: 'Navegacao principal', previousFeatured: 'Drama em destaque anterior', nextFeatured: 'Proximo drama em destaque' }),
  fr: localize({ home: 'Accueil', search: 'Rechercher', library: 'Ma liste', profile: 'Profil', featured: 'A la une', continue: 'Continuer a regarder', browse: 'Explorer par humeur', trending: 'Tendances', fresh: 'Nouveaux episodes', discover: 'Votre prochaine histoire commence ici.', discoverCopy: 'Des dramas courts pour les moments entre deux activites.', seeAll: 'Tout voir', stories: 'histoires', views: 'vues', watched: 'regarde', episodes: 'episodes', episode: 'Episode', free: 'GRATUIT', watchAd: 'Voir une pub pour debloquer', watchNow: 'Regarder maintenant', details: 'Details', about: 'A propos de ce drama', like: 'J aime', liked: 'Aime', save: 'Enregistrer', saved: 'Enregistre', share: 'Partager', signIn: 'Se connecter avec TikTok', signInCopy: 'Reprenez votre lecture, collectionnez vos favoris et debloquez des episodes partout.', guest: 'Visiteur', history: 'Vus recemment', favorites: 'Favoris', settings: 'Parametres', language: 'Langue', autoplay: 'Lire automatiquement le prochain episode', reducedData: 'Reduire l utilisation des donnees', continueWithoutTapping: 'Continuer sans toucher', useLessData: 'Utiliser moins de donnees media', noHistory: 'Votre historique apparaitra ici.', noFavorites: 'Enregistrez un drama pour creer votre liste.', back: 'Retour', retry: 'Reessayer', noResults: 'Aucun drama ne correspond a cette recherche.', tryThese: 'Essayez plutot ceci', searchPlaceholder: 'Rechercher des dramas ou genres', clearSearch: 'Effacer la recherche', findNextStory: 'Trouvez votre prochaine histoire.', searchByTitleMoodGenre: 'Recherchez par titre, humeur ou genre.', upNext: 'A suivre', syncing: 'Synchronisation...', unlockFailed: 'Echec du deverrouillage. Reessayez.', unavailable: 'Ce drama est indisponible.', openingDrama: 'Ouverture du drama...', preparingEpisode: 'Preparation de votre episode...', searching: 'Recherche...', updatingPlayback: 'Mise a jour de la lecture', rewardedAdRequired: 'Publicite recompensee requise', playable: 'Disponible', unlockEpisode: 'Debloquer l episode', watchEpisode: 'Regarder l episode', welcome: 'BIENVENUE', member: 'MEMBRE QUICKREEL' }),
  id: localize({ home: 'Beranda', search: 'Cari', library: 'Daftar saya', profile: 'Profil', featured: 'Pilihan', continue: 'Lanjut menonton', browse: 'Jelajahi suasana', trending: 'Sedang populer', fresh: 'Episode baru', discover: 'Cerita favorit berikutnya dimulai di sini.', discoverCopy: 'Drama pendek untuk mengisi waktu di antara kesibukan.', seeAll: 'Lihat semua', stories: 'cerita', views: 'tayangan', watched: 'ditonton', episodes: 'episode', episode: 'Episode', free: 'GRATIS', watchAd: 'Tonton iklan untuk membuka', watchNow: 'Tonton sekarang', details: 'Detail', about: 'Tentang drama ini', like: 'Suka', liked: 'Disukai', save: 'Simpan', saved: 'Tersimpan', share: 'Bagikan', signIn: 'Masuk dengan TikTok', signInCopy: 'Simpan posisi, kumpulkan favorit, dan buka episode di semua perangkat.', guest: 'Penonton tamu', history: 'Baru ditonton', favorites: 'Favorit', settings: 'Pengaturan', language: 'Bahasa', autoplay: 'Putar episode berikutnya otomatis', reducedData: 'Kurangi penggunaan data', continueWithoutTapping: 'Lanjut tanpa mengetuk', useLessData: 'Gunakan lebih sedikit data media', noHistory: 'Riwayat tontonan akan muncul di sini.', noFavorites: 'Simpan drama untuk membuat daftar.', back: 'Kembali', retry: 'Coba lagi', noResults: 'Tidak ada drama yang cocok.', tryThese: 'Coba salah satu ini', searchPlaceholder: 'Cari drama atau genre', clearSearch: 'Hapus pencarian', findNextStory: 'Temukan cerita berikutnya.', searchByTitleMoodGenre: 'Cari berdasarkan judul, suasana, atau genre.', upNext: 'Berikutnya', syncing: 'Menyinkronkan...', unlockFailed: 'Gagal membuka. Coba lagi.', unavailable: 'Drama ini tidak tersedia.', openingDrama: 'Membuka drama...', preparingEpisode: 'Menyiapkan episode...', searching: 'Mencari...', updatingPlayback: 'Memperbarui info pemutaran', rewardedAdRequired: 'Iklan berhadiah diperlukan', playable: 'Bisa diputar', unlockEpisode: 'Buka episode', watchEpisode: 'Tonton episode', welcome: 'SELAMAT DATANG', member: 'ANGGOTA QUICKREEL' }),
  ja: localize({ home: 'ホーム', search: '検索', library: 'マイリスト', profile: 'プロフィール', featured: 'おすすめ', continue: '視聴を続ける', browse: '気分から探す', trending: '人気作品', fresh: '新着エピソード', discover: '次のお気に入りがここから始まります。', discoverCopy: 'すきま時間に楽しめるショートドラマ。', seeAll: 'すべて見る', stories: '作品', views: '回視聴', watched: '視聴済み', episodes: 'エピソード', episode: '第', free: '無料', watchAd: '広告を見てロック解除', watchNow: '今すぐ見る', details: '詳細', about: 'このドラマについて', like: 'いいね', liked: 'いいね済み', save: '保存', saved: '保存済み', share: '共有', signIn: 'TikTokでログイン', signInCopy: '視聴位置やお気に入りを保存し、どの端末でもエピソードを楽しめます。', guest: 'ゲスト', history: '最近見た作品', favorites: 'お気に入り', settings: '設定', language: '言語', autoplay: '次のエピソードを自動再生', reducedData: 'データ使用量を減らす', continueWithoutTapping: 'タップせずに続ける', useLessData: 'メディアデータを節約', noHistory: '視聴履歴がここに表示されます。', noFavorites: 'ドラマを保存してリストを作成しましょう。', back: '戻る', retry: '再試行', noResults: '一致するドラマがありません。', tryThese: 'こちらをお試しください', searchPlaceholder: 'ドラマやジャンルを検索', clearSearch: '検索をクリア', findNextStory: '次の物語を見つけよう。', searchByTitleMoodGenre: 'タイトル、気分、ジャンルで検索', upNext: '次に見る', syncing: '同期中...', unlockFailed: '解除できませんでした。もう一度お試しください。', unavailable: 'このドラマは利用できません。', openingDrama: 'ドラマを開いています...', preparingEpisode: 'エピソードを準備中...', searching: '検索中...', updatingPlayback: '再生情報を更新中', rewardedAdRequired: '広告視聴が必要', playable: '再生可能', unlockEpisode: 'エピソードを解除', watchEpisode: 'エピソードを見る', welcome: 'ようこそ', member: 'QUICKREEL メンバー' }),
  es: localize({ home: 'Inicio', search: 'Buscar', library: 'Mi lista', profile: 'Perfil', featured: 'Destacados', continue: 'Continuar viendo', browse: 'Explorar por animo', trending: 'Tendencias', fresh: 'Nuevos episodios', discover: 'Tu proxima historia comienza aqui.', discoverCopy: 'Dramas cortos para los momentos entre todo lo demas.', seeAll: 'Ver todo', stories: 'historias', views: 'vistas', watched: 'visto', episodes: 'episodios', episode: 'Episodio', free: 'GRATIS', watchAd: 'Ver anuncio para desbloquear', watchNow: 'Ver ahora', details: 'Detalles', about: 'Sobre este drama', like: 'Me gusta', liked: 'Te gusta', save: 'Guardar', saved: 'Guardado', share: 'Compartir', signIn: 'Iniciar sesion con TikTok', signInCopy: 'Guarda tu progreso, colecciona favoritos y desbloquea episodios en todos tus dispositivos.', guest: 'Espectador invitado', history: 'Visto recientemente', favorites: 'Favoritos', settings: 'Ajustes', language: 'Idioma', autoplay: 'Reproducir el siguiente episodio automaticamente', reducedData: 'Reducir uso de datos', continueWithoutTapping: 'Continuar sin tocar', useLessData: 'Usar menos datos multimedia', noHistory: 'Tu historial aparecera aqui.', noFavorites: 'Guarda un drama para crear tu lista.', back: 'Volver', retry: 'Reintentar', noResults: 'Ningun drama coincide con la busqueda.', tryThese: 'Prueba una de estas opciones', searchPlaceholder: 'Buscar dramas o generos', clearSearch: 'Borrar busqueda', findNextStory: 'Encuentra tu proxima historia.', searchByTitleMoodGenre: 'Busca por titulo, animo o genero.', upNext: 'A continuacion', syncing: 'Sincronizando...', unlockFailed: 'No se pudo desbloquear. Intentalo de nuevo.', unavailable: 'Este drama no esta disponible.', openingDrama: 'Abriendo drama...', preparingEpisode: 'Preparando tu episodio...', searching: 'Buscando...', updatingPlayback: 'Actualizando informacion de reproduccion', rewardedAdRequired: 'Se requiere anuncio recompensado', playable: 'Disponible', unlockEpisode: 'Desbloquear episodio', watchEpisode: 'Ver episodio', welcome: 'BIENVENIDO', member: 'MIEMBRO DE QUICKREEL' }),
  ko: localize({ home: '홈', search: '검색', library: '내 목록', profile: '프로필', featured: '추천', continue: '이어서 보기', browse: '분위기로 둘러보기', trending: '인기작', fresh: '새 에피소드', discover: '다음 이야기가 여기서 시작됩니다.', discoverCopy: '바쁜 순간 사이에 즐기는 짧은 드라마.', seeAll: '모두 보기', stories: '작품', views: '조회', watched: '시청함', episodes: '에피소드', episode: '에피소드', free: '무료', watchAd: '광고를 보고 잠금 해제', watchNow: '지금 보기', details: '상세 정보', about: '이 드라마에 대해', like: '좋아요', liked: '좋아요함', save: '저장', saved: '저장됨', share: '공유', signIn: 'TikTok으로 로그인', signInCopy: '시청 위치와 즐겨찾기를 저장하고 모든 기기에서 에피소드를 잠금 해제하세요.', guest: '게스트 시청자', history: '최근 시청', favorites: '즐겨찾기', settings: '설정', language: '언어', autoplay: '다음 에피소드 자동 재생', reducedData: '데이터 사용량 줄이기', continueWithoutTapping: '탭하지 않고 계속하기', useLessData: '미디어 데이터 절약', noHistory: '시청 기록이 여기에 표시됩니다.', noFavorites: '드라마를 저장해 목록을 만들어 보세요.', back: '뒤로', retry: '다시 시도', noResults: '검색 결과가 없습니다.', tryThese: '다음 작품을 확인해 보세요', searchPlaceholder: '드라마 또는 장르 검색', clearSearch: '검색 지우기', findNextStory: '다음 이야기를 찾아보세요.', searchByTitleMoodGenre: '제목, 분위기 또는 장르로 검색하세요.', upNext: '다음 재생', syncing: '동기화 중...', unlockFailed: '잠금 해제에 실패했습니다. 다시 시도하세요.', unavailable: '이 드라마를 이용할 수 없습니다.', openingDrama: '드라마를 여는 중...', preparingEpisode: '에피소드 준비 중...', searching: '검색 중...', updatingPlayback: '재생 정보 업데이트 중', rewardedAdRequired: '보상형 광고 필요', playable: '재생 가능', unlockEpisode: '에피소드 잠금 해제', watchEpisode: '에피소드 보기', welcome: '환영합니다', member: 'QUICKREEL 회원' }),
  th: localize({ home: 'หน้าหลัก', search: 'ค้นหา', library: 'รายการของฉัน', profile: 'โปรไฟล์', featured: 'แนะนำ', continue: 'ดูต่อ', browse: 'เลือกตามอารมณ์', trending: 'กำลังมาแรง', fresh: 'ตอนใหม่', discover: 'เรื่องถัดไปของคุณเริ่มที่นี่', discoverCopy: 'ซีรีส์สั้นสำหรับช่วงเวลาระหว่างวัน', seeAll: 'ดูทั้งหมด', stories: 'เรื่อง', views: 'การดู', watched: 'ดูแล้ว', episodes: 'ตอน', episode: 'ตอนที่', free: 'ฟรี', watchAd: 'ดูโฆษณาเพื่อปลดล็อก', watchNow: 'ดูเลย', details: 'รายละเอียด', about: 'เกี่ยวกับซีรีส์นี้', like: 'ถูกใจ', liked: 'ถูกใจแล้ว', save: 'บันทึก', saved: 'บันทึกแล้ว', share: 'แชร์', signIn: 'เข้าสู่ระบบด้วย TikTok', signInCopy: 'บันทึกตำแหน่งการชม เก็บรายการโปรด และปลดล็อกตอนต่างๆ ในทุกอุปกรณ์', guest: 'ผู้ชมทั่วไป', history: 'ดูล่าสุด', favorites: 'รายการโปรด', settings: 'การตั้งค่า', language: 'ภาษา', autoplay: 'เล่นตอนถัดไปอัตโนมัติ', reducedData: 'ลดการใช้ข้อมูล', continueWithoutTapping: 'ดูต่อโดยไม่ต้องแตะ', useLessData: 'ใช้ข้อมูลสื่อน้อยลง', noHistory: 'ประวัติการชมจะแสดงที่นี่', noFavorites: 'บันทึกซีรีส์เพื่อสร้างรายการของคุณ', back: 'กลับ', retry: 'ลองอีกครั้ง', noResults: 'ไม่พบซีรีส์ที่ตรงกับการค้นหา', tryThese: 'ลองดูเรื่องเหล่านี้', searchPlaceholder: 'ค้นหาซีรีส์หรือแนวเรื่อง', clearSearch: 'ล้างการค้นหา', findNextStory: 'ค้นหาเรื่องถัดไปของคุณ', searchByTitleMoodGenre: 'ค้นหาตามชื่อ อารมณ์ หรือแนวเรื่อง', upNext: 'ถัดไป', syncing: 'กำลังซิงค์...', unlockFailed: 'ปลดล็อกไม่สำเร็จ กรุณาลองอีกครั้ง', unavailable: 'ซีรีส์นี้ไม่พร้อมใช้งาน', openingDrama: 'กำลังเปิดซีรีส์...', preparingEpisode: 'กำลังเตรียมตอนของคุณ...', searching: 'กำลังค้นหา...', updatingPlayback: 'กำลังอัปเดตข้อมูลการเล่น', rewardedAdRequired: 'ต้องดูโฆษณาเพื่อรับสิทธิ์', playable: 'เล่นได้', unlockEpisode: 'ปลดล็อกตอน', watchEpisode: 'ดูตอน', welcome: 'ยินดีต้อนรับ', member: 'สมาชิก QUICKREEL' })
};

Object.assign(messages.pt, { moreToWatch: 'Mais para assistir', navigation: 'Navegacao principal', previousFeatured: 'Drama em destaque anterior', nextFeatured: 'Proximo drama em destaque' });
Object.assign(messages.fr, { moreToWatch: 'Plus a regarder', navigation: 'Navigation principale', previousFeatured: 'Drama precedent', nextFeatured: 'Drama suivant' });
Object.assign(messages.id, { moreToWatch: 'Lebih banyak untuk ditonton', navigation: 'Navigasi utama', previousFeatured: 'Drama unggulan sebelumnya', nextFeatured: 'Drama unggulan berikutnya' });
Object.assign(messages.ja, { moreToWatch: 'もっと見る', navigation: 'メインナビゲーション', previousFeatured: '前のおすすめ作品', nextFeatured: '次のおすすめ作品' });
Object.assign(messages.es, { moreToWatch: 'Mas para ver', navigation: 'Navegacion principal', previousFeatured: 'Drama destacado anterior', nextFeatured: 'Siguiente drama destacado' });
Object.assign(messages.ko, { moreToWatch: '더 볼 작품', navigation: '기본 탐색', previousFeatured: '이전 추천 드라마', nextFeatured: '다음 추천 드라마' });
Object.assign(messages.th, { moreToWatch: 'เรื่องน่าดูเพิ่มเติม', navigation: 'การนำทางหลัก', previousFeatured: 'ซีรีส์แนะนำก่อนหน้า', nextFeatured: 'ซีรีส์แนะนำถัดไป' });

export type { MessageKey };
export function t(locale: Locale, key: MessageKey): string { return messages[locale]?.[key] ?? messages.en[key]; }
const genreLabels: Partial<Record<Locale, Record<string, string>>> = {
  pt: { romance: 'Romance', revenge: 'Vinganca', fantasy: 'Fantasia', thriller: 'Suspense', power: 'Poder' },
  fr: { romance: 'Romance', revenge: 'Vengeance', fantasy: 'Fantaisie', thriller: 'Thriller', power: 'Pouvoir' },
  id: { romance: 'Romantis', revenge: 'Balas dendam', fantasy: 'Fantasi', thriller: 'Thriller', power: 'Kekuatan' },
  ja: { romance: 'ロマンス', revenge: '復讐', fantasy: 'ファンタジー', thriller: 'スリラー', power: '権力' },
  es: { romance: 'Romance', revenge: 'Venganza', fantasy: 'Fantasia', thriller: 'Suspenso', power: 'Poder' },
  ko: { romance: '로맨스', revenge: '복수', fantasy: '판타지', thriller: '스릴러', power: '권력' },
  th: { romance: 'โรแมนติก', revenge: 'แก้แค้น', fantasy: 'แฟนตาซี', thriller: 'ระทึกขวัญ', power: 'อำนาจ' }
};
export function translateGenre(locale: Locale, slug: string) { return genreLabels[locale]?.[slug.toLowerCase()] ?? slug; }
export function detectLocale(): Locale {
  const language = navigator.language.toLowerCase();
  if (language.startsWith('pt')) return 'pt'; if (language.startsWith('fr')) return 'fr'; if (language.startsWith('id')) return 'id'; if (language.startsWith('ja')) return 'ja'; if (language.startsWith('es')) return 'es'; if (language.startsWith('ko')) return 'ko'; if (language.startsWith('th')) return 'th'; return 'en';
}
